
sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew build -x test

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/rafaresearch/SimianArmy/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-345ad9513aafff397050d613fa87ad06ddffe99d
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            